odamex/odamex

- common/p_map.cpp
This fix also prevents grunt1 sound from playing.
> SPECTATOR: Fixes bouncing as a flying spectator. (+1 fix)

- CMakeLists.txt
- client/src/c_console.cpp
The reason is a few commits can strangely extend 7 characters, making the console crash because of an unexpected overflow.
Also, I limited the git describing to 6 characters, to better respect regular git standards, when it comes to show them.
> Safeprinting the version of Odamex in the console

- common/p_map.cpp
Indeed, after further and much deeper testings, the server or client crashed when a player dies, respawn, but the previous corpse continues to slide. Since this condition wasn't checked, the server crashed. My bad.
> Fixes a crash related to the slidemo pointer

- client/sdl/i_sdlvideo.cpp
Apparently, I managed to make one of my compilations unsuccessful because of
that line.
Besides, every other statement to _XBOX has been stated under
define(_XBOX), except this one.
also, _WIN32 should be used instead of WIN32 alone.
> Change a #if statement to #ifdef in i_sdlvideo

- client/src/st_new.cpp
If you pickup a Berzerk while using the ZDOOM HUD, you are now notified by replacing the Medkit to the Berzerk one.
> ZDOOM HUD: Berzerk icon is replacing the medikit if having one.

- client/src/v_draw.cpp
This CVAR was still able to display the HUD elements at an extremely low percentage, even if the CVAR was set to 0.
This PR fixes it.
> Fixing hud_transparancy CVAR 

- client/src/cl_main.cpp
Whenever Odamex plays their own demoformat, it sets "simulated_connection" to true.
However, whenever this variable is true, it makes packet sending/receiving impossible, thus making an infinite "conn,ecting to..." loop. 
This PR fixes that issue, by resetting this value to "false" whenever the connect CMD is used.
> fix an "connecting to" infinite loop

- client/sdl/i_video.cpp
- client/sdl/i_video.h
- client/src/v_video.cpp
Only call V_Init to change video resolution / parameters if a parameter is actually changed. This fixes a V_Init flicker when sv_allowwidescreen is sent to clients.
> No V_Init on cvar changes

- client/src/cl_main.cpp
- server/src/sv_main.cpp
This PR fixes the issue at this link: https://odamex.net/bugs/show_bug.cgi?id=1108
> Spy mode now displays keys people have on COOP mode.

- common/w_ident.cpp
FreeDoom IWADs from 0.10 up to 0.11.3 are now recognized by Odamex.
> FreeDoom IWADs updates

- client/src/c_bind.cpp
- client/src/c_bind.h
- client/src/hu_elements.cpp
This PR creates a new function in C_BIND.cpp (C_GetKeyStringsFromCommand) that tells you what buttons you use from a bind.
That created, I used it on the "Warmup: you are not ready" so that it says "Warmup: press <KEYBINDS> to ready up".
> Add keys to the Warmup message

- common/p_pspr.cpp
- common/p_spec.cpp
- server/src/d_main.cpp
- server/src/sv_maplist.cpp
> Removes the double localized "You need a XXX key" from the server.
This is a fix that disables the message spread from the server to the client. Besides, I don't get why that part of code was created. So, I just assume it was for testing purposes, but is troublesome otherwise, if the PWAD uses custom messages.
For some reason, that said message is also spread from the server's locale (check PR #31 to also remove that). So for instance, it'll be displayed in French even if the user's language is in english.
> Several various minor to major fixes 

- server/src/sv_main.cpp
Whenever you use "playerinfo" without an argument serverside, it'll always throw you a "Bad player number" for nothing. Instead, I corrected it by informing you how to use it.
Also added time to playerlist info (used by many other ports/games).
> SV: "Playerinfo" CMD is friendlier now.

- common/c_cvarlist.cpp
- server/src/i_system.cpp
- Forces ENGLISH as the language of the server.
- Fixes `language` CVAR being seen as a boolean, while technically accepting up to 256 languages. (yet it doesn't though)
> Language fixes

- client/src/g_game.cpp
- common/c_cvarlist.cpp
- common/p_mobj.cpp
Initially, Odamex doesn't respawn Invulnerability and partial invisibility. This commit fixes it by adding a new CVAR.
Also, fixes a small grammatical mistake in a CVAR.
> Add sv_respawnsuper CVAR.

- client/src/cl_main.cpp
Clear the moving sectors when going from in game back to spectator so that moving sectors do not appear stuck.
> Fix for bug 1067

- client/src/c_bind.cpp
- client/src/hu_stuff.cpp
- client/src/hu_stuff.h
Added HU_ReleaseKeyStates to release the alt key when the windows gains focus back. This fixes the alt+tab chat bug for when pressing numbers: I'm not looking to good!
> Fix for bug 1262

- client/src/cl_cvarlist.cpp
- client/src/cl_main.cpp
- client/src/d_netinfo.cpp
- client/src/m_options.cpp
- common/d_netinf.h
- server/src/sv_main.cpp
Removed obsolete P_AtInterval(3) for destroying moving sectors.
Removed any code relating cl_updaterate and the update_rate variable in the player structure. The clients can no longer change the tic interval they are updated.
> Fix for bug 1265

- common/d_main.cpp
- common/p_tick.cpp
- Odamex now pauses in Singleplayer if you bring down the console.
- Odamex's framelimit is perfectly uncapped while playing a demo and after bringing down the console (or open the menu).
> Framerate & console fixes.

- common/p_user.cpp
When using GOD mode, you can still drown in deepwater.
This PR fixes it.
> GOD mode won't make us drown anymore.

- client/src/cl_main.cpp
- client/src/cl_stubs.cpp
- common/doomdef.h
- common/p_acs.cpp
- common/p_ctf.h
- common/p_inter.h
- common/p_interaction.cpp
- common/p_lnspec.cpp
- server/src/sv_ctf.cpp
- server/src/sv_main.cpp
Added ItemEquipVal so we can tell if the item was equipped and/or needs to be removed. This allows us to send pickup sounds to clients for co_globalsound. The clients are no longer calculating pickup sounds from other players. Since server sends the sound the client will no longer mistakenly play a weapon pickup when the server would not.
> Send weapon/item pickup sounds to clients when co_globalsound is enabled

- server/src/sv_cvarlist.cpp
I thought some another cvar ruled on that one. As a result, it made teams an absolute minimal of 1 player (as 0 meant "unlimited").
> Revert sv_maxplayersperteam minimum value.

- client/src/cl_main.cpp
- client/src/cl_mobj.cpp
- common/p_pspr.cpp
As pointed out in the Bug Tracker here ( https://odamex.net/bugs/show_bug.cgi?id=1245 ) , Odamex actually desyncs during a few deathmatch demos.
This PR partially fixes them.
> Fixing classic demo desyncs.

- client/src/cl_main.cpp
- common/p_spec.cpp
- common/p_spec.h
- common/p_switch.cpp
- common/r_defs.h
- server/src/g_level.cpp
- server/src/sv_main.cpp
Destroy sector move and sound effects when resetting on client.
Fixed svc_switch to include special, switchactive, and button texture if
applicable so the client syncs properly with the server.
Client will no longer play switch sound when initially syncing with
server.
Fixes bugs:
https://odamex.net/bugs/show_bug.cgi?id=1281
https://odamex.net/bugs/show_bug.cgi?id=1205
https://odamex.net/bugs/show_bug.cgi?id=1102
https://odamex.net/bugs/show_bug.cgi?id=1267
> Sector/switch client/server desync fixes.

- common/g_level.cpp
Fixes:
https://odamex.net/bugs/show_bug.cgi?id=1266
> Skip when hitting invalid syntax, otherwise pointer addition is invalid.

- client/src/cl_main.cpp
- server/src/sv_main.cpp
Since no action has been done (was merged in protobreak), I'm redoing a pull request, this time on the development branch for 0.8.1 .
> (RE)Keys are now shown when spying on Coop.

- client/src/cl_main.cpp
I fixed the teams wrongly translated after changing a team.
When you do switch teams, you're sending the command after changing the CVAR, but BEFORE the server acknoledges you're switching teams. As a result, colors are messed up.
Fixes bug 1234 : https://odamex.net/bugs/show_bug.cgi?id=1234
> Fix for forced colors after switching teams (Bug #1234)

- common/p_map.cpp
With co_realactorheights , two players can still enter each other if there's a height difference.
This PR fixes it.
> Fix co_realactorheights and player in-between collisions.

- client/src/cl_main.cpp
When playing a demo AFTER JOINING a server, if you want to reconnect, or disconnect and try to reconnect, it'll loop forever.
This PR fixes more of it.
> Fixed more bad cases of "simulated connection"

- common/d_player.h
- common/p_interaction.cpp
- server/src/g_level.cpp
- server/src/sv_main.cpp
death_time was reset after each respawn, making suicide spam entirely possible.
This PR fixes that issue by addressing a new variable specifically tailored for this purpose.
> Fix suicide spam

- client/sdl/i_sdlvideo.cpp
- client/sdl/i_sdlvideo.h
Select the most preferred driver that is actually supported by the user's system. Additionally, if the most preferred driver is OpenGL, include the SDL_WINDOW_OPENGL flag when creating the SDL Window. This was already the case on Win32 but was omitted in Linux systems, resulting in crashes when creating the SDL Renderer instance.
> Improve selection of SDL2 renderer drivers. 

- common/p_enemy.cpp
Duplicates how vanilla Doom II did it: just remove the spawning cube when it has an invalid target (which it has after loading)
Fixes https://odamex.net/bugs/show_bug.cgi?id=1302
> Fix Icon of Sin save game crash

- appveyor_after_build.ps1
- appveyor_before_build.ps1
Enabled Windows XP (winxp) build compatibility for appyveyor builds.
include MSVC runtime DLLs for x86 winxp compatibility.
> Client: enable Windows XP compatibility

- client/src/g_game.cpp
- Fix a fatal crash when you try recording a vanilla demo after playing online.
- Also fixed demos not properly closing after recording.
> Vanilla demos recording fixes

- client/src/r_things.cpp
The weapon was shown one pixel higher. This PR fixes it.
> Fix the weapon's sprite's offset.

- common/d_player.h
- server/src/sv_main.cpp
server: short-cut clc_wantwad to resume download without expensive MD5 checks.
Without this short-cut, the server will constantly keep recomputing the MD5 hash of the requested WAD whenever the client misses a packet. This causes the CPU utilization to climb to 100% easily when packet loss is high.
> Server: prevent DoS during WAD downloading

- client/src/c_console.cpp
Fix "msg" cvar to not be a boolean to fix message level filtering.
This now enables the third option in the message filtering menu option which was previously inaccessible due to the absence of the CVAR_NOENABLEDISABLE flag, forcing the value to a boolean 0 or 1 case.
> Client: fix msg cvar to not be a boolean

- client/src/c_bind.cpp
In earlier builds, all keys not in lowercase weren't recognized by the port.
This PR fixes it, by converting all argv[1] arguments to bind commands to lowercase.
> Lowercase all key arguments during bind commands

- client/src/cl_main.cpp
Added `spyname` command for convenience of spying players by name instead of id.
try to actively spy on named player when they reconnect, e.g. level changes.
spyname with no args unfollows player and will disable spy mode
> Client: spyname command

- client/src/m_options.cpp
client: increase number of steps adjusting snd_sfxvolume, snd_musicvolume, and snd_announcervolume to 64; 1.0/64 = 0.015625. Total number of steps supported by SDL_mixer is 128 so 64 steps in the menu slider is plenty. I would really like to see dB units being used here instead of 0..1 or 128 steps but SDL_mixer is the limiting factor here.
> Client: more volume steps in sound options menu

- client/src/v_draw.cpp
client: adjust scaling factor by +1 only in non-integral cases; fixes console font rendering to be 1:1 pixels when scaling is not needed.
> Client: fix scaling factor for DCanvas::DrawSWrapper

- common/d_main.cpp
- common/p_spec.h
- common/p_switch.cpp
- server/src/sv_main.cpp
SV_WriteCommands() was calling SV_UpdateHiddenMobj() from a foreach player loop; SV_UpdateHiddenMobj() has its own foreach player loop; moved the SV_UpdateHiddenMobj() function out of the foreach player loop in SV_WriteCommands() which drastically reduces server CPU utilization according to playtesting.
Replaced I_Yield() call in D_RunTics() for SERVER_APP with explicit I_Sleep() and calculated sleep duration. This reduces unnecessary CPU utilization because I_Yield() simply loops and sleeps for 1ms each loop iteration.
optimized poor performance of SV_ClientFullUpdate() updating switch/button state: introduced new P_UpdateButtons() function to iterate efficiently through all switch objects.
More efficient std::queue clearing by swapping with empty instance instead of while(!empty){pop()} …
> Server: performance fixes for O(n^2) loops

- client/src/cl_main.cpp
client: fix NET_SendMessage message too long error
> Client: fix NET_SendMessage message too long error

- appveyor.yml
Shaves about 50-60 seconds off the build times compared to non-parallel.
> Appveyor enable parallel builds

- CMakeLists.txt
- appveyor.yml
- appveyor_before_build.ps1
- common/doomtype.h
cmake: define _CRT_SECURE_NO_WARNINGS for MSVC compilers
appveyor: cache SDL2 downloads and extraction
Remove redundant compiler warnings (270 of them all the same).
> Appveyor optimizations

- common/d_dehacked.cpp
- common/doomtype.h
- common/info.cpp
- common/info.h
- common/p_enemy.cpp
- common/p_mobj.cpp
- common/p_pspr.cpp
This is an attempt to fix the custom pinkie crash in Valiant, but the scope got a little wider past that.
Essentially, the custom pinkie uses a state index that Odamex simply does not have.  In theory, this change could be fixed by adding a bunch of blank states, like what happened in Woof and Graf's fork of prBoom+.  However, I decided to go a little bit above and beyond and stub out the missing MBF codepointers and mobj types as well.  This ensures that the final boss of Valiant, which uses the helper dog mobj, works as well.
Most of the other MBF code pointers are stubbed out, because the important ones that ZDoom gives first class support for already exist.  I also did not add any default graphics or sounds for the mobjs to the WAD either, since that might give the impression that …
> Bug #1236, plus additional stubs

- common/p_setup.cpp
While testing the new duel queue, I was running the server with Address Sanitizer and it caught a pretty nasty bug in `P_CreateBlockMap()`.  The stack trace should be self-explanatory.
```
[18:47:47] ========== Odamex Server Initialized ==========
[18:47:48] --- MAP00: "START" ---
=================================================================
==7328==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs operator delete []) on 0x6020000156b0
#0 0x7f151543ac40 in operator delete[](void*) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xebc40)
#1 0x55cc18fdb6ed in P_CreateBlockMap() ../common/p_setup.cpp:1364
#2 0x55cc18fdbbc3 in P_LoadBlockMap(int) ../common/p_setup.cpp:1388
#3 0x55cc18fde152 in P_SetupLevel(char*, int) ../common/p_setup.cpp:1752
#4 0x55cc190c619a in …
```
> Delete linelist_t with delete and not delete[] in P_CreateBlockMap

- wad/CMakeLists.txt
The odamex.wad file should be built in the proper build directory;
building in the source tree confuses CMake and causes it to attempt to
rebuild a second time.
> Fix odamex.wad build flow

- client/src/cl_ctf.cpp
Fix drawing "hud_heldflag" border around the view window when the status bar is visible and vid_320x200 or vid_640x400 is enabled.
> Fix drawing "hud_heldflag" border around the view window

- common/d_main.cpp
Some Linux distributions such as Gentoo keep their WAD files under the
/usr/share/doom directory by default. Let's add that location to the
search paths too.
> Add /usr/share/doom search path

- wad/CMakeLists.txt
The odamex.wad file shouldn't be listed in BYPRODUCTS because it's
already listed as the OUTPUT of the add_custom_command.
> Remove duplicate build rule for odamex.wad

- client/src/c_console.cpp
- client/src/cl_main.cpp
- client/src/m_options.cpp
- common/doomtype.h
- common/i_net.cpp
- common/m_memio.h
- common/p_mobj.cpp
- server/src/c_console.cpp
This PR changes the name of my `COUNTOF` Array Length macro (that I contributed with my first MBF fix patch) to `ARRAY_LENGTH` to be more clear and gets rid of the old `STACKARRAY_LENGTH ` macro that was vulnerable to misuse.
> COUNTOF and STACKARRAY_LENGTH to ARRAY_LENGTH

- client/src/cl_main.cpp
- client/src/cl_stubs.cpp
- common/p_interaction.cpp
- server/src/sv_main.cpp
- server/src/sv_main.h
If the svc_damageplayer packet was resent after a player respawned then that player would be damaged on the client but not the server.
This update sends the player mobj's netid instead, so if they respawn and receive the svc_damageplayer command out of order it will fail to find the player.
This update also sends the health/armor damage amounts so the client can subtract them rather the player's health/armor. This will prevent desyncs where the client can get an older damage message after a newer one, which would incorrectly increase the players health/armor.
> send net id instead of player id for svc_damageplayer

- client/src/hu_elements.cpp
This is a small cosmetic modification, it adds an ordinal suffix to the HUD message displayed when a client is waiting in the join queue, changing "Position in line to play: N" into "Waiting to play - Nth in line".
> Slightly modify the HUD message while waiting in the queue

- common/p_doors.cpp
- common/p_floor.cpp
- common/p_pillar.cpp
- common/p_plats.cpp
Resolves bug caused by specials with looping sounds never stopping. This happened because the sector prediction would destroy the special but predicting sectors wouldn't stop the sound. This fix prevents the special from being destroyed so the next run think can stop the sound.
> do not destroy specials while predicting

- common/p_teleport.cpp
Pretty simple - the height-aware teleport broke at some point in the past and and this commit fixes it.
> Fix for z-teleports height not working

- client/src/cl_main.cpp
- common/i_net.h
- common/p_switch.cpp
- server/src/sv_main.cpp
Destroy switch thinkers on CL_ResetMap, otherwise active switches set during a map reset will be stuck. Also prevent repeat switches from playing the switch sound on destroy.
Send svc_fullupdatestart so the client can correctly reset the recv_full_update variable, so single use switches are set to the appropriate texture.
> switch desync fixes

- common/p_lnspec.cpp
- common/p_spec.cpp
Prevent ACS from executing client side when connected to server. Previously scrips would execute on the client and then again when the client receives the line special activation from the server. This would cause scripts with print messages to double print, but has much worse de-sync potential depending on what specials the script would activate.
> Prevent ACS from executing client side when connected to server

- client/src/cl_main.cpp
- client/src/cl_stubs.cpp
- client/src/g_game.cpp
- client/src/g_level.cpp
- common/c_cvarlist.cpp
- common/d_items.cpp
- common/d_items.h
- common/p_interaction.cpp
- server/src/g_game.cpp
- server/src/g_level.cpp
- server/src/sv_main.cpp
- server/src/sv_main.h
When a key has been found by a player, share that key to all players.
I'ved also removed the CVAR_LATCH property in sv_keepkeys, it has no reason to be there.
Original bug thread : https://odamex.net/bugs/show_bug.cgi?id=1248
> [BUG #1248] sv_sharekeys CVAR

- common/p_xlat.cpp
This is something I noticed in Valiant MAP01 - some of the lifts that make hidden monsters appear don't work.  After looking into it, this is a simple oversight in the existing code that incorrectly classifies a floor special as a ceiling special.
This is technically backwards incompatible, as it is possible for clients and servers to disagree on the position of the floor.  However, in my testing between mismatched client and server, nothing crashes, there's just possibilities for mispredictions, and considering that the prior behavior was straight up broken I don't really consider said mispredictions a problem, so I think that it is safe to merge into `development`.
Considering that getting Valiant working without crashes requires a protobreak patch, here is a test WAD you can use to see …
> Ensure special 24576 is considered a floor special

- client/src/cl_main.cpp
- client/src/cl_main.h
- client/src/cl_maplist.h
- client/src/cl_stubs.cpp
- common/i_net.cpp
- common/i_net.h
- common/p_acs.cpp
- common/p_acs.h
- common/p_lnspec.cpp
- common/p_spec.cpp
- server/src/sv_main.cpp
- server/src/sv_main.h
- server/src/sv_rproto.cpp
The server now controls all ACS execution and sends commands to client(s) via svc_executelinespecial and svc_executeacsspecial.
svc_executeacsspecial is expandable and allows for a variable number of int parameters and an optional string for printing functions. The variable int parameters are packed to take up the least amount of bytes (e.g an integer value of 64 will only take one byte).
This also includes some minor fixes for ACS functions found along the way for inventory functions and DPlaneWatcher.
> Server controls ACS execution

- common/p_pspr.cpp
Update P_GetNextWeapon and P_CheckSwitchWeapon to handle readyweapon/pendingweapon set to NUMWEAPONS from ClearInventory/TakeInventory
> Fix crash caused by weapon cycling after ClearInventory

- common/d_dehacked.cpp
One of the text substitutions asserted fewer characters than were actually there, which led to GetLine() bombing out because it tried to make sense of the end of the string substitution.
I solved the immediate problem by using `igets()` to munch the rest of the line safely.  However, GetLine really should be fixed-up to do bounds-checking and lay off some of the migraine-inducing post-increment stunts it does like`*line++ = 0;`.  I'd do it, but I'd rather wait until the `MAPINFO` and `LANGUAGE` improvements are in `development`, since there are some unfortunate interactions that happen between DeHackEd and `LANGUAGE` that makes debugging text substitutions difficult right now.
> Fix ASAN DeHackEd crash on UDMX

- common/p_user.cpp
In my testing in unrelated branches, I ran into two different crashes that I believe were caused by the use of uninitialized memory in the `player_s` struct.  Both of them seemed to be triggered by loading a savegame, but not every time.  One of them was an address sanitizer crash, the other one was a genuine crash that didn't seem to be detected by ASan.
I rewrote the constructor to use a member initializer list and also ensure that every single element in the player struct is populated.
> Fix two bugs caused by lacking initialization of player struct

- client/src/cl_main.cpp
- client/src/cl_main.h
- client/src/r_plane.cpp
- common/dsectoreffect.h
- common/i_net.h
- common/p_acs.cpp
- common/p_lights.cpp
- common/p_lnspec.cpp
- common/p_lnspec.h
- common/p_spec.cpp
- common/p_spec.h
- common/r_defs.h
- server/src/d_main.cpp
- server/src/r_plane.cpp
- server/src/sv_main.cpp
Sync server map state with client on connection.
Client will not execute sector, line, and sidedef changes unless instructed by the server. This includes light thinkers and scrollers.
Server keeps track of sector, line, and sidedef changes.
This change is mostly required for ACS changing map state. However, this does fix certain vanilla cases. For example, connecting after the light change special E1M3 would cause the client to have the wrong sector brightness.
svc_sectorproperties, svc_linesideupdate, and svc_thinkerupdate use sub-types so we do not need to eat all the svc_* commands for every property that changed.
For example, svc_sectorproperties writes the flags in the next short of what properties changed in the sector. This allows all sector property changes to be written in the …
> Sync map state

- client/src/c_console.cpp
This PR adds zsh-style tab-completion.
- Upon hitting tab while typing a partial command, the console will calculate all possible completions and complete up to the longest unambiguous sub-string.  It will then render a list of possible completions above the command line.
- The possible completions are presented in columns, and up to five lines worth of completions are printed.  If there are more, it will say so.
- At this point, hitting tab will insert a completion candidate.  Hitting tab again will cycle to the next completion candidate.  Hitting shift-tab will cycle back to the previous completion candidate.  If you move the cursor, this sort of tab-cycling state will cease.
- Note that these completions are presented in a sort of "buffer" between the normal console output and the …
> Improve tab-completion

- common/CMakeLists.txt
```
CMake Error at common/CMakeLists.txt:7 (target_sources):
Cannot specify sources for imported target "odamex-common".
CMake Error at common/CMakeLists.txt:8 (target_include_directories):
Cannot specify include directories for imported target "odamex-common".
```
This PR fixes this bug in CMake 3.10.
> Fix an error that pops up in CMake 3.10

- client/sdl/i_system.cpp
- client/sdl/i_system.h
- client/src/c_console.cpp
- common/c_cvars.cpp
- common/cmdlib.cpp
- common/cmdlib.h
- common/doomtype.h
- server/src/c_console.cpp
- server/src/i_system.h
This patch introduces wrapper defines for two GCC "attributes".  One of them checks the formatting of printf-style functions, and the other annotates a function as not returning, which should squelch warnings that arise from the compiler incorrectly assuming it can advance past a noreturn function call.
`FORMAT_PRINTF` was applied to the three print functions and `StrFormat`.  `NORETURN` was applied to `I_FatalError`.  MSVC has an equivalent for noreturn, but not for format, and the define accounts for this.
> Add GCC attributes to functions

- odalaunch/CMakeLists.txt
This addresses bug #1311. wxWidgets 3.0.4 requires C++11 support.
> Use C++11 on odalaunch target for wx 3.0.4 and up

- client/sdl/i_sound.cpp
The short version is contained in the comment:
```
// Apparently, when Mix_OpenAudio requests a certain number of channels
// and the device claims to not support that number of channels, instead
// of handling it automatically behind the scenes, Mixer might initialize
// with a broken audio buffer instead.  Using this function instead works
// around the problem.
```
The long version is here: https://github.com/chocolate-doom/chocolate-doom/pull/1309  Thanks to Edward850 for hipping me to this issue.
> Use Mix_OpenAudioDevice on SDL2

- client/src/v_screenshot.cpp
- client/src/v_video.cpp
- Don't check widescreen while shutting down.
- Ensure text string buffers are in-scope while writing PNG screenshots.
> Fix two ASan bugs

- common/p_setup.cpp
This was causing an amazing bug where crossing the line occupied by a transparent texture would cause all of the 2s lines on the map to become more transparent.
Funny bug, one line fix, what's not to love.
> Don't activate transparency lines

- common/doomtype.h
- common/z_zone.cpp
`inttypes.h` has several PRI* defines used to print format specifiers, and keeping with this convention I introduced a format define specifically for size_t.  It uses `I` on MSVC and `z` elsewhere.
Hopefully this means we can finally nix some format specifier warnings.  I nixed all of them in `z_zone.cpp` as an example.
> Introduce PRIuSIZE and related defines

- client/src/cl_main.cpp
If the client gets one of these packets without a level loaded, things go haywire and the client starts crashing.
Discovered during testing of `http-dl`.
> Fix up CL_ThinkerUpdate

- client/src/st_new.cpp
Should fix instances of Z_ChangeTag errors on quit.
> Clear the freelist after tagging it as cachable

- client/src/cl_demo.cpp
- client/src/cl_main.cpp
- client/src/g_game.cpp
I think I figured out what was causing HOM when playing a netdemo.
First off, the newly-spawned player did not have a camera, so their head was somewhere in the void, or if you were terribly unlucky, the position where the player on the map before netplay began.
Next, `viewz` was not being recorded in the demo.  Normally, this would not be a problem, since it gets initialized upon player spawn, but the demo machinery reloads the map when first starting and `viewz` is reset to 1 without being reset by another player spawn.  There's probably a more elegant way to fix this, but writing `viewz` works well enough for now.
> Fix a few bugs causing HOM on netplay

- CMakeLists.txt
- README
- Xbox/README.Xbox
- ag-odalaunch/res/Info.plist
- client/sdl/client.rc
- client/src/c_console.cpp
- client/src/m_misc.cpp
- common/git_describe.h.in
- common/version.cpp
- common/version.h
- installer/windows/odamex.iss
- odalaunch/res/Info.plist
- odalaunch/res/gui_project.fbp
- odalaunch/res/odalaunch.rc
- odalpapi/net_packet.h
- server/src/sv_sqp.cpp
- server/win32/server.rc
This PR essentially bumps the version to 0.9.0.
I think this should be done to `protobreak` the moment we do a stable release of Odamex, to ensure that standard clients don't attempt to connect to `protobreak` servers we run in the future.
I also worked in a couple of version-related extras, to clean up the look of `version` and the version displayed in the console.
> Bump version to 0.9.0

- client/src/g_game.cpp
- client/src/r_interp.cpp
- client/src/r_main.cpp
The improved mouse code I believe exposed an issue where turning with the keyboard and joystick stopped working, and looking up and down was incredibly jittery.
I believe this PR fixes both issues.  Now, we interpolate if there is no accumulated yaw or pitch values, and we also fix a bug where accumulated yaw was blasting away any other types of yaw.
> Fix looking around with keyboard/joystick

- client/src/c_console.cpp
- client/src/cl_cvarlist.cpp
- client/src/cl_main.cpp
- client/src/cl_stubs.cpp
- client/src/d_netinfo.cpp
- client/src/m_options.cpp
- client/src/st_stuff.cpp
- common/g_gametype.cpp
- common/g_gametypecmd.cpp
- common/i_net.h
- common/msg_server.cpp
- common/msg_server.h
- server/src/sv_main.cpp
The following PR fixes a few bugs discovered: 
- Fix the statbar to not render tens of lives
- Improved the hud_revealsecrets behaviour online
- Fix Teamkill messages not being displayed
- Display a message in case of an invalid client
- Fix attempt to crash when a player tries to join an unknown team
- Fix serverside CVARs being forced-reset by the client when resetting to default
> Miscellanous fixes

- client/src/cl_main.cpp
- server/src/sv_main.cpp
This PR does the following:
- changeteams' maxvalue is synced with the server
- Disallow serverside green spawning on classic CTF
- The server doesn't forceteam spectators anymore.
> More Teams fixes

- client/src/am_map.cpp
- client/src/c_console.cpp
- client/src/cl_main.cpp
- client/src/cl_stubs.cpp
- client/src/g_level.cpp
- client/src/st_new.cpp
- common/g_level.h
- common/g_levelstate.cpp
- common/i_net.h
- common/msg_server.cpp
- common/p_enemy.cpp
- common/p_mobj.cpp
- common/p_setup.cpp
- server/src/g_level.cpp
- server/src/sv_main.cpp
- server/src/sv_main.h
This PR does the following:
- Fix an OoB found with ASAN and msgmid.
- Properly synchronize total monsters online and respawned monsters.
- Fix the Archvile resurrecting sound for clients. (it isn't played at all)
- Add Lives counter to ZDoom HUD.
- Changed slightly the Match-Broadcasted message in case of a Coop game.
(it's the last one, I swear! 👀)
> More... More Fixes for Misc-Fixes

- client/src/am_map.cpp
- client/src/cl_demo.cpp
- client/src/cl_main.cpp
- client/src/cl_mobj.cpp
- client/src/hu_elements.cpp
- client/src/hu_stuff.cpp
- client/src/r_interp.cpp
- common/g_gametype.cpp
- common/g_levelstate.cpp
- common/p_interaction.cpp
- common/p_user.cpp
- server/src/g_game.cpp
- server/src/g_level.cpp
- server/src/sv_main.cpp
- server/src/sv_pickup.cpp
- server/src/sv_sqp.cpp
- server/src/sv_sqpold.cpp
This PR does the following:
- Freeze the timer during a warmup, if sv_timelimit is set.
- Give 1 round point for the defending team if `g_sides` is enabled and the timelimit is hit.
- Fixes the new cameraangle interpolation in case of demoplayback.
- Fix softlocks when 1 player on a team has no more lives, and another from the same team leaves/is kicked/spectates.
- Clamp `cl_team` CVAR if the value is higher than sv_teamsinplay.
- Fix alive players to be able to spectate players who don't have lives anymore.
> More and more bugfixes, part Deux

- client/src/r_things.cpp
- common/r_defs.h
Support for an extra 8 frames to look at an object from in between the existing frames. Tested with teapot16.wad, code reworked using Doom Retro as a guide.
> Add support 16 rotational frame sprites

- server/src/g_level.cpp
On coop/survival mode, found keys are added to an array `keysfound`. However, whenever the game must restart on survival (because everyone lost), the array isn't cleared.
As a result, if `sv_sharekeys` is enabled, everyone will get the keys on the newest round, breaking the purpose of the gamemode.
This PR fixes this issue.
> Reset found keys on survival after a game lost.

- client/src/g_game.cpp
- server/src/g_game.cpp
Since G_PlayerReborn is called whenever a game is restarted, all spectators have their CF_FLY flag removed, forcing them to the ground. Of course, this is absolutely an unintended behaviour.
This PR **only** disable cheats for non-spectators.
> Restore FLY ability to spectators after a game starts.
